before_script:
  - phpenv config-rm xdebug.ini
  - printf "\n" | pecl install -f apcu
cache:
  directories:
    - $HOME/.composer/cache/files
env:
  global:
    - MAKEFLAGS="-j 2"
language: php
script: make check
