version: "3"
services:
  pg1:
    environment:
      POSTGRES_PASSWORD: drowssap
    image: postgres
  web1:
    build: .
    depends_on:
      - pg1
    environment:
      DATABASE_URL: pgsql://postgres:drowssap@pg1:5432/safe
    volumes:
      - .:/app
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
